# Generated by Django 3.1.4 on 2021-01-02 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Tanım')),
                ('completed', models.BooleanField(default=True, verbose_name='Durum')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Zaman')),
            ],
        ),
    ]
